//
//  UIColor+RTRAdditions.swift
//
//  Generated by Zeplin on 10/8/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
	class var rtrWhite: UIColor { 
		return UIColor(white: 255.0 / 255.0, alpha: 1.0)
	}

	class var rtrPumpkinOrange: UIColor {
		return UIColor(red: 255.0 / 255.0, green: 110.0 / 255.0, blue: 16.0 / 255.0, alpha: 1.0)
	}

	class var rtrOrangeyRed70: UIColor {
		return UIColor(red: 249.0 / 255.0, green: 63.0 / 255.0, blue: 45.0 / 255.0, alpha: 0.7)
	}

	class var rtrAzure70: UIColor {
		return UIColor(red: 0.0, green: 170.0 / 255.0, blue: 236.0 / 255.0, alpha: 0.7)
	}

	class var rtrDenimBlue70: UIColor {
		return UIColor(red: 56.0 / 255.0, green: 86.0 / 255.0, blue: 147.0 / 255.0, alpha: 0.7)
	}

	class var rtrBlack10: UIColor { 
		return UIColor(white: 0.0, alpha: 0.1)
	}

	class var rtrSunYellow80: UIColor {
		return UIColor(red: 248.0 / 255.0, green: 230.0 / 255.0, blue: 27.0 / 255.0, alpha: 0.8)
	}

	class var rtrWhite80: UIColor { 
		return UIColor(white: 255.0 / 255.0, alpha: 0.8)
	}

	class var rtrGreyishBrown: UIColor {
		return UIColor(red: 77.0 / 255.0, green: 71.0 / 255.0, blue: 65.0 / 255.0, alpha: 1.0)
	}

	class var rtrGreyishBrown80: UIColor {
		return UIColor(red: 99.0 / 255.0, green: 90.0 / 255.0, blue: 80.0 / 255.0, alpha: 0.8)
	}

	class var rtrWhite90: UIColor { 
		return UIColor(white: 255.0 / 255.0, alpha: 0.9)
	}

	class var rtrPurpleyGrey: UIColor {
		return UIColor(red: 143.0 / 255.0, green: 142.0 / 255.0, blue: 148.0 / 255.0, alpha: 1.0)
	}

	class var rtrSunYellow: UIColor {
		return UIColor(red: 248.0 / 255.0, green: 231.0 / 255.0, blue: 28.0 / 255.0, alpha: 1.0)
	}

	class var rtrBlack60: UIColor { 
		return UIColor(white: 0.0, alpha: 0.6)
	}

	class var rtrWhite13: UIColor { 
		return UIColor(white: 255.0 / 255.0, alpha: 0.13)
	}

	class var rtrWhite30: UIColor { 
		return UIColor(white: 255.0 / 255.0, alpha: 0.3)
	}

	class var rtrPumpkinOrangeTwo: UIColor {
		return UIColor(red: 255.0 / 255.0, green: 114.0 / 255.0, blue: 13.0 / 255.0, alpha: 1.0)
	}

	class var rtrDodgerBlue: UIColor {
		return UIColor(red: 66.0 / 255.0, green: 133.0 / 255.0, blue: 244.0 / 255.0, alpha: 1.0)
	}

	class var rtrBlack: UIColor { 
		return UIColor(white: 0.0, alpha: 1.0)
	}

	class var rtrMediumGreen: UIColor {
		return UIColor(red: 52.0 / 255.0, green: 168.0 / 255.0, blue: 83.0 / 255.0, alpha: 1.0)
	}

	class var rtrMarigold: UIColor {
		return UIColor(red: 251.0 / 255.0, green: 188.0 / 255.0, blue: 5.0 / 255.0, alpha: 1.0)
	}

	class var rtrTomato: UIColor {
		return UIColor(red: 234.0 / 255.0, green: 67.0 / 255.0, blue: 53.0 / 255.0, alpha: 1.0)
	}

	class var rtrDusk80: UIColor {
		return UIColor(red: 83.0 / 255.0, green: 98.0 / 255.0, blue: 140.0 / 255.0, alpha: 0.8)
	}

	class var rtrGreyishBrown50: UIColor {
		return UIColor(red: 99.0 / 255.0, green: 90.0 / 255.0, blue: 80.0 / 255.0, alpha: 0.5)
	}

	class var rtrBlackTwo: UIColor { 
		return UIColor(white: 24.0 / 255.0, alpha: 1.0)
	}

	class var rtrBlack20: UIColor { 
		return UIColor(white: 0.0, alpha: 0.2)
	}

	class var rtrCharcoalGrey: UIColor {
		return UIColor(red: 61.0 / 255.0, green: 62.0 / 255.0, blue: 64.0 / 255.0, alpha: 1.0)
	}

	class var rtrCoolGreyTwo: UIColor {
		return UIColor(red: 145.0 / 255.0, green: 151.0 / 255.0, blue: 163.0 / 255.0, alpha: 1.0)
	}

	class var rtrSilver: UIColor {
		return UIColor(red: 214.0 / 255.0, green: 217.0 / 255.0, blue: 224.0 / 255.0, alpha: 1.0)
	}

	class var rtrGreyishBrownTwo: UIColor {
		return UIColor(red: 99.0 / 255.0, green: 90.0 / 255.0, blue: 80.0 / 255.0, alpha: 1.0)
	}

	class var rtrSteel: UIColor {
		return UIColor(red: 142.0 / 255.0, green: 142.0 / 255.0, blue: 147.0 / 255.0, alpha: 1.0)
	}

	class var rtrBlackThree: UIColor { 
		return UIColor(white: 3.0 / 255.0, alpha: 1.0)
	}

	class var rtrWhiteTwo: UIColor { 
		return UIColor(white: 244.0 / 255.0, alpha: 1.0)
	}

	class var rtrWhiteTwo80: UIColor { 
		return UIColor(white: 252.0 / 255.0, alpha: 0.8)
	}

	class var rtrWhite50: UIColor { 
		return UIColor(white: 255.0 / 255.0, alpha: 0.5)
	}

	class var rtrOrangeRed: UIColor {
		return UIColor(red: 254.0 / 255.0, green: 56.0 / 255.0, blue: 36.0 / 255.0, alpha: 1.0)
	}

	class var rtrGreyishBrownThree: UIColor { 
		return UIColor(white: 77.0 / 255.0, alpha: 1.0)
	}

	class var rtrDark: UIColor {
		return UIColor(red: 20.0 / 255.0, green: 24.0 / 255.0, blue: 35.0 / 255.0, alpha: 1.0)
	}

	class var rtrBlack50: UIColor { 
		return UIColor(white: 0.0, alpha: 0.5)
	}

	class var rtrBrightBlue: UIColor {
		return UIColor(red: 0.0, green: 118.0 / 255.0, blue: 255.0 / 255.0, alpha: 1.0)
	}

	class var rtrGreyishBrownThree78: UIColor { 
		return UIColor(white: 77.0 / 255.0, alpha: 0.78)
	}

	class var rtrCoolGrey60: UIColor {
		return UIColor(red: 171.0 / 255.0, green: 179.0 / 255.0, blue: 189.0 / 255.0, alpha: 0.6)
	}

	class var rtrCoolGrey30: UIColor {
		return UIColor(red: 171.0 / 255.0, green: 179.0 / 255.0, blue: 189.0 / 255.0, alpha: 0.3)
	}

	class var rtrCoolGrey50: UIColor {
		return UIColor(red: 171.0 / 255.0, green: 179.0 / 255.0, blue: 189.0 / 255.0, alpha: 0.5)
	}

	class var rtrWhite10: UIColor { 
		return UIColor(white: 255.0 / 255.0, alpha: 0.1)
	}

	class var rtrGunmetal: UIColor {
		return UIColor(red: 78.0 / 255.0, green: 86.0 / 255.0, blue: 101.0 / 255.0, alpha: 1.0)
	}

	class var rtrWhiteTwo90: UIColor { 
		return UIColor(white: 250.0 / 255.0, alpha: 0.9)
	}

	class var rtrBlack30: UIColor { 
		return UIColor(white: 0.0, alpha: 0.3)
	}

	class var rtrBrownGrey: UIColor {
		return UIColor(red: 147.0 / 255.0, green: 131.0 / 255.0, blue: 114.0 / 255.0, alpha: 1.0)
	}

	class var rtrCoolGreyThree: UIColor {
		return UIColor(red: 157.0 / 255.0, green: 165.0 / 255.0, blue: 177.0 / 255.0, alpha: 1.0)
	}

	class var rtrCoolGrey: UIColor {
		return UIColor(red: 144.0 / 255.0, green: 153.0 / 255.0, blue: 167.0 / 255.0, alpha: 1.0)
	}

	class var rtrWhiteThree: UIColor { 
		return UIColor(white: 216.0 / 255.0, alpha: 1.0)
	}

	class var rtrWhiteTwo30: UIColor { 
		return UIColor(white: 230.0 / 255.0, alpha: 0.3)
	}

	class var rtrBlackThree9: UIColor { 
		return UIColor(white: 3.0 / 255.0, alpha: 0.09)
	}

	class var rtrPurplishGrey: UIColor {
		return UIColor(red: 122.0 / 255.0, green: 121.0 / 255.0, blue: 123.0 / 255.0, alpha: 1.0)
	}

	class var rtrCharcoalGrey50: UIColor {
		return UIColor(red: 60.0 / 255.0, green: 62.0 / 255.0, blue: 64.0 / 255.0, alpha: 0.5)
	}

	class var rtrDarkTwo: UIColor {
		return UIColor(red: 29.0 / 255.0, green: 29.0 / 255.0, blue: 38.0 / 255.0, alpha: 1.0)
	}

	class var rtrGreyishBrownFour: UIColor {
		return UIColor(red: 72.0 / 255.0, green: 71.0 / 255.0, blue: 69.0 / 255.0, alpha: 1.0)
	}

	class var rtrCoolGreyFour: UIColor {
		return UIColor(red: 167.0 / 255.0, green: 169.0 / 255.0, blue: 172.0 / 255.0, alpha: 1.0)
	}

	class var rtrBeige: UIColor {
		return UIColor(red: 249.0 / 255.0, green: 245.0 / 255.0, blue: 236.0 / 255.0, alpha: 1.0)
	}

	class var rtrSilverTwo: UIColor {
		return UIColor(red: 200.0 / 255.0, green: 199.0 / 255.0, blue: 204.0 / 255.0, alpha: 1.0)
	}

	class var rtrSlateGrey: UIColor {
		return UIColor(red: 109.0 / 255.0, green: 109.0 / 255.0, blue: 114.0 / 255.0, alpha: 1.0)
	}

	class var rtrOrangeRedTwo: UIColor {
		return UIColor(red: 255.0 / 255.0, green: 58.0 / 255.0, blue: 48.0 / 255.0, alpha: 1.0)
	}

	class var rtrSilverThree: UIColor {
		return UIColor(red: 199.0 / 255.0, green: 199.0 / 255.0, blue: 204.0 / 255.0, alpha: 1.0)
	}

	class var rtrDusk: UIColor {
		return UIColor(red: 84.0 / 255.0, green: 98.0 / 255.0, blue: 140.0 / 255.0, alpha: 1.0)
	}

	class var rtrCharcoalGreyTwo: UIColor {
		return UIColor(red: 64.0 / 255.0, green: 66.0 / 255.0, blue: 68.0 / 255.0, alpha: 1.0)
	}
}
