//
//  UIFont+RTRAdditions.swift
//
//  Generated by Zeplin on 10/8/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIFont {
	class func rtrTextStyle12Font() -> UIFont? {
		return UIFont(name: "GothamMedium", size: 48.0)
	}

	class func rtrTextStyle13Font() -> UIFont? {
		return UIFont(name: "GothamMedium", size: 48.0)
	}

	class func rtrTextStyle14Font() -> UIFont? {
		return UIFont(name: "GothamMedium", size: 48.0)
	}

	class func rtrTextStyle15Font() -> UIFont? {
		return UIFont(name: "GothamMedium", size: 48.0)
	}

	class func rtrTextStyleFont() -> UIFont? {
		return UIFont(name: "GothamBook", size: 48.0)
	}

	class func rtrTextStyle5Font() -> UIFont? {
		return UIFont(name: "AppleSDGothicNeo-Medium", size: 22.0)
	}

	class func rtrTextStyle9Font() -> UIFont {
		return UIFont.systemFont(ofSize: 22.0, weight: UIFontWeightRegular)
	}

	class func rtrTextStyle2Font() -> UIFont? {
		return UIFont(name: "AppleSDGothicNeo-Regular", size: 18.0)
	}

	class func rtrTextStyle4Font() -> UIFont? {
		return UIFont(name: "AppleSDGothicNeo-Regular", size: 18.0)
	}

	class func rtrTextStyle10Font() -> UIFont? {
		return UIFont(name: "AppleSDGothicNeo-Regular", size: 17.0)
	}

	class func rtrTextStyle8Font() -> UIFont {
		return UIFont.systemFont(ofSize: 17.0, weight: UIFontWeightLight)
	}

	class func rtrTextStyle11Font() -> UIFont {
		return UIFont.systemFont(ofSize: 17.0, weight: UIFontWeightLight)
	}

	class func rtrTextStyle3Font() -> UIFont? {
		return UIFont(name: "AppleSDGothicNeo-Bold", size: 14.0)
	}

	class func rtrTextStyle6Font() -> UIFont? {
		return UIFont(name: "AppleSDGothicNeo-Regular", size: 14.0)
	}

	class func rtrTextStyle16Font() -> UIFont? {
		return UIFont(name: "AppleSDGothicNeo-Regular", size: 14.0)
	}

	class func rtrTextStyle7Font() -> UIFont {
		return UIFont.systemFont(ofSize: 14.0, weight: UIFontWeightRegular)
	}
}
